In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('covid_vaccine_statewise.csv')

In [4]:
df

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7840,11/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7841,12/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7842,13/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7843,14/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7844,15/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.columns

Index(['Updated On', 'State', 'Total Doses Administered', 'Sessions',
       ' Sites ', 'First Dose Administered', 'Second Dose Administered',
       'Male (Doses Administered)', 'Female (Doses Administered)',
       'Transgender (Doses Administered)', ' Covaxin (Doses Administered)',
       'CoviShield (Doses Administered)', 'Sputnik V (Doses Administered)',
       'AEFI', '18-44 Years (Doses Administered)',
       '45-60 Years (Doses Administered)', '60+ Years (Doses Administered)',
       '18-44 Years(Individuals Vaccinated)',
       '45-60 Years(Individuals Vaccinated)',
       '60+ Years(Individuals Vaccinated)', 'Male(Individuals Vaccinated)',
       'Female(Individuals Vaccinated)', 'Transgender(Individuals Vaccinated)',
       'Total Individuals Vaccinated'],
      dtype='object')

In [6]:
df.describe()

,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),Covaxin (Doses Administered),CoviShield (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
count,7.621000e+03,7.621000e+03,7621.000000,7.621000e+03,7.621000e+03,7.461000e+03,7.461000e+03,7461.000000,7.621000e+03,7.621000e+03,...,1.702000e+03,1.702000e+03,1.702000e+03,3.733000e+03,3.734000e+03,3.734000e+03,1.600000e+02,1.600000e+02,160.000000,5.919000e+03
mean,9.188171e+06,4.792358e+05,2282.872064,7.414415e+06,1.773755e+06,3.620156e+06,3.168416e+06,1162.978019,1.044669e+06,8.126553e+06,...,8.773958e+06,7.442161e+06,5.641605e+06,1.395895e+06,2.916515e+06,2.627444e+06,4.461687e+07,3.951018e+07,12370.543750,4.547842e+06
std,3.746180e+07,1.911511e+06,7275.973730,2.995209e+07,7.570382e+06,1.737938e+07,1.515310e+07,5931.353995,4.452259e+06,3.298414e+07,...,2.660829e+07,2.225999e+07,1.681650e+07,5.501454e+06,9.567607e+06,8.192225e+06,3.950749e+07,3.417684e+07,12485.026753,1.834182e+07
min,7.000000e+00,0.000000e+00,0.000000,7.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000,0.000000e+00,7.000000e+00,...,2.662400e+04,1.681500e+04,9.994000e+03,1.059000e+03,1.136000e+03,5.580000e+02,2.375700e+04,2.451700e+04,2.000000,7.000000e+00
25%,1.356570e+05,6.004000e+03,69.000000,1.166320e+05,1.283100e+04,5.655500e+04,5.210700e+04,8.000000,0.000000e+00,1.331340e+05,...,4.344842e+05,2.326275e+05,1.285605e+05,5.655400e+04,9.248225e+04,5.615975e+04,5.739350e+06,5.023407e+06,1278.750000,7.427550e+04
50%,8.182020e+05,4.547000e+04,597.000000,6.614590e+05,1.388180e+05,3.897850e+05,3.342380e+05,113.000000,1.185100e+04,7.567360e+05,...,3.095970e+06,2.695938e+06,1.805696e+06,2.947270e+05,8.330395e+05,7.887425e+05,3.716590e+07,3.365402e+07,8007.500000,4.022880e+05
75%,6.625243e+06,3.428690e+05,1708.000000,5.387805e+06,1.166434e+06,2.735777e+06,2.561513e+06,800.000000,7.579300e+05,6.007817e+06,...,7.366241e+06,6.969726e+06,5.294763e+06,9.105160e+05,2.499280e+06,2.337874e+06,7.441663e+07,6.685368e+07,19851.000000,3.501562e+06
max,5.132284e+08,3.501031e+07,73933.000000,4.001504e+08,1.130780e+08,2.701636e+08,2.395186e+08,98275.000000,6.236742e+07,4.468251e+08,...,2.243304e+08,1.667575e+08,1.186927e+08,9.224315e+07,9.096888e+07,6.731098e+07,1.349420e+08,1.156684e+08,46462.000000,2.506569e+08

In [7]:
df[df['State'] == 'India']

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,11/08/2021,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,12/08/2021,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,13/08/2021,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,14/08/2021,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,15/08/2021,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
import numpy as np

In [9]:
states = np.unique(df['State'])

In [10]:
mh = df[df['State'] == 'Maharashtra']

In [11]:
mh['First Dose Administered'].sum()

2784364331.0

In [12]:
for state in states:
    temp = df[df['State'] == state]
    print(state, temp['First Dose Administered'].sum())

Andaman and Nicobar Islands 16425854.0
Andhra Pradesh 1232860845.0
Arunachal Pradesh 49004980.0
Assam 585600226.0
Bihar 1470502878.0
Chandigarh 44703105.0
Chhattisgarh 796002902.0
Dadra and Nagar Haveli and Daman and Diu 33595063.0
Delhi 624339473.0
Goa 75991368.0
Gujarat 2131646009.0
Haryana 755798352.0
Himachal Pradesh 316294004.0
India 28262144791.0
Jammu and Kashmir 410101777.0
Jharkhand 603673726.0
Karnataka 1873329968.0
Kerala 1193845072.0
Ladakh 17809249.0
Lakshadweep 4363655.0
Madhya Pradesh 1796604591.0
Maharashtra 2784364331.0
Manipur 67409568.0
Meghalaya 62615974.0
Mizoram 47873077.0
Nagaland 42410766.0
Odisha 1032633168.0
Puducherry 41346858.0
Punjab 584346582.0
Rajasthan 2201044187.0
Sikkim 36980929.0
Tamil Nadu 1288532512.0
Telangana 880320645.0
Tripura 192689726.0
Uttar Pradesh 2788411358.0
Uttarakhand 363191446.0
West Bengal 1796449989.0

In [13]:
df

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7840,11/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7841,12/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7842,13/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7843,14/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7844,15/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7845 entries, 0 to 7844
Data columns (total 24 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Updated On                           7845 non-null   object
 1   State                                7845 non-null   object
 2   Total Doses Administered             7621 non-null   float64
 3   Sessions                             7621 non-null   float64
 4    Sites                               7621 non-null   float64
 5   First Dose Administered              7621 non-null   float64
 6   Second Dose Administered             7621 non-null   float64
 7   Male (Doses Administered)            7461 non-null   float64
 8   Female (Doses Administered)          7461 non-null   float64
 9   Transgender (Doses Administered)     7461 non-null   float64
 10   Covaxin (Doses Administered)        7621 non-null   float64
 11  CoviShield (Doses Administered)      7621 non-null   float64
 12  Sputnik V (Doses Administered)       2995 non-null   float64
 13  AEFI                                 5438 non-null   float64
 14  18-44 Years (Doses Administered)     1702 non-null   float64
 15  45-60 Years (Doses Administered)     1702 non-null   float64
 16  60+ Years (Doses Administered)       1702 non-null   float64
 17  18-44 Years(Individuals Vaccinated)  3733 non-null   float64
 18  45-60 Years(Individuals Vaccinated)  3734 non-null   float64
 19  60+ Years(Individuals Vaccinated)    3734 non-null   float64
 20  Male(Individuals Vaccinated)         160 non-null    float64
 21  Female(Individuals Vaccinated)       160 non-null    float64
 22  Transgender(Individuals Vaccinated)  160 non-null    float64
 23  Total Individuals Vaccinated         5919 non-null   float64
dtypes: float64(22), object(2)
memory usage: 1.4+ MB

In [15]:
df[df['Updated On'] == '09/08/2021']

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
205,09/08/2021,India,513228400.0,21978176.0,46163.0,400150406.0,113077994.0,270163622.0,239518609.0,98275.0,...,224330364.0,166757453.0,118692689.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
417,09/08/2021,Andaman and Nicobar Islands,310643.0,5325.0,31.0,216046.0,94597.0,165554.0,145049.0,40.0,...,118865.0,128122.0,63656.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
629,09/08/2021,Andhra Pradesh,23842895.0,926449.0,1732.0,17628583.0,6214312.0,10852932.0,12986129.0,3834.0,...,7169390.0,10746667.0,5926838.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
841,09/08/2021,Arunachal Pradesh,879094.0,31506.0,129.0,692475.0,186619.0,486874.0,391993.0,227.0,...,514163.0,263660.0,101271.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1053,09/08/2021,Assam,12703870.0,718900.0,1690.0,10495293.0,2208577.0,6739027.0,5962985.0,1858.0,...,6661719.0,4109188.0,1932963.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1265,09/08/2021,Bihar,27834939.0,1151080.0,1096.0,23350171.0,4484768.0,14926420.0,12902990.0,5529.0,...,13984649.0,7520647.0,6329643.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,09/08/2021,Chandigarh,923819.0,24131.0,66.0,700285.0,223534.0,524263.0,399424.0,132.0,...,486854.0,274475.0,162490.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1689,09/08/2021,Chhattisgarh,11769177.0,1390084.0,1027.0,9181482.0,2587695.0,5916437.0,5851349.0,1391.0,...,4389004.0,4705765.0,2674408.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1901,09/08/2021,Dadra and Nagar Haveli and Daman and Diu,665221.0,47210.0,70.0,584370.0,80851.0,444656.0,220429.0,136.0,...,474123.0,144345.0,46753.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2113,09/08/2021,Delhi,10836082.0,302853.0,1311.0,7835546.0,3000536.0,6228216.0,4605508.0,2358.0,...,5444642.0,3397825.0,1993615.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2326,09/08/2021,Goa,1396911.0,55237.0,56.0,1094392.0,302519.0,748770.0,648014.0,127.0,...,676052.0,413810.0,307049.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2538,09/08/2021,Gujarat,37152375.0,1008804.0,3360.0,28101222.0,9051153.0,20266401.0,16880326.0,5648.0,...,16854786.0,11912298.0,8385291.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2750,09/08/2021,Haryana,13010381.0,513427.0,1128.0,10086831.0,2923550.0,7206601.0,5801370.0,2410.0,...,6331770.0,3596240.0,3082371.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2962,09/08/2021,Himachal Pradesh,5632441.0,162941.0,701.0,4249849.0,1382592.0,2772475.0,2858812.0,1154.0,...,2216211.0,1970847.0,1445383.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3174,09/08/2021,Jammu and Kashmir,6808342.0,687590.0,1724.0,5318516.0,1489826.0,3919555.0,2887608.0,1179.0,...,2418624.0,2727353.0,1662365.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3386,09/08/2021,Jharkhand,10378294.0,374667.0,995.0,8382280.0,1996014.0,5699723.0,4676520.0,2051.0,...,5144231.0,3078646.0,2155417.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3598,09/08/2021,Karnataka,33280543.0,2972686.0,4958.0,25847691.0,7432852.0,16724770.0,16550206.0,5567.0,...,14653045.0,10803056.0,7824442.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3810,09/08/2021,Kerala,22097731.0,586973.0,1365.0,15670747.0,6426984.0,10623457.0,11470142.0,4132.0,...,6467292.0,7612487.0,8017952.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4022,09/08/2021,Ladakh,259036.0,5980.0,16.0,188699.0,70337.0,146068.0,112942.0,26.0,...,133710.0,70230.0,55096.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4234,09/08/2021,Lakshadweep,68295.0,6800.0,11.0,51156.0,17139.0,37277.0,31013.0,5.0,...,31333.0,23734.0,13228.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4446,09/08/2021,Madhya Pradesh,35456676.0,1682473.0,3762.0,29723036.0,5733640.0,19265405.0,16184296.0,6975.0,...,19289779.0,9903544.0,6263353.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4658,09/08/2021,Maharashtra,47153366.0,1300638.0,3896.0,35040812.0,12112554.0,25563569.0,21582082.0,7715.0,...,18155358.0,16275265.0,12722743.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4870,09/08/2021,Manipur,1406118.0,120142.0,143.0,1159424.0,246694.0,759282.0,646498.0,338.0,...,781364.0,403277.0,221477.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5082,09/08/2021,Meghalaya,1170554.0,152390.0,461.0,938572.0,231982.0,618575.0,551829.0,150.0,...,682701.0,345939.0,141914.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5294,09/08/2021,Mizoram,861719.0,20557.0,37.0,654946.0,206773.0,433324.0,428257.0,138.0,...,439688.0,260548.0,161483.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5506,09/08/2021,Nagaland,791508.0,35729.0,90.0,632120.0,159388.0,451752.0,339640.0,116.0,...,467353.0,214623.0,109532.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5718,09/08/2021,Odisha,18154686.0,625969.0,1464.0,13954592.0,4200094.0,9617376.0,8533720.0,3590.0,...,7378863.0,6116468.0,4659355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5930,09/08/2021,Puducherry,753362.0,85653.0,64.0,601591.0,151771.0,367047.0,386171.0,144.0,...,365729.0,233589.0,154044.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6142,09/08/2021,Punjab,10291265.0,1022020.0,1690.0,8005636.0,2285629.0,5734736.0,4555264.0,1265.0,...,4419059.0,3348278.0,2523928.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6354,09/08/2021,Rajasthan,35383662.0,803717.0,1920.0,27008606.0,8375056.0,18618674.0,16758710.0,6278.0,...,15113858.0,10832586.0,9437218.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6566,09/08/2021,Sikkim,649389.0,9478.0,25.0,497851.0,151538.0,354056.0,295116.0,217.0,...,352027.0,189808.0,107554.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6778,09/08/2021,Tamil Nadu,25522708.0,790804.0,1654.0,20836674.0,4686034.0,12952604.0,12565628.0,4476.0,...,12838090.0,7815365.0,4869253.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6990,09/08/2021,Telangana,15614892.0,525374.0,1403.0,11649268.0,3965624.0,8068394.0,7543612.0,2886.0,...,7067455.0,5356758.0,3190679.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7202,09/08/2021,Tripura,3215294.0,211896.0,665.0,2411195.0,804099.0,1646249.0,1568576.0,469.0,...,1396211.0,1189107.0,629976.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7414,09/08/2021,Uttar Pradesh,54447724.0,2621580.0,4845.0,45932488.0,8515236.0,30643444.0,23785865.0,18415.0,...,26583720.0,17007044.0,10856960.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7626,09/08/2021,Uttarakhand,6667116.0,130940.0,492.0,5070544.0,1596572.0,3405375.0,3259384.0,2357.0,...,3063316.0,2022265.0,1581535.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7838,09/08/2021,West Bengal,32390378.0,866173.0,2086.0,23257417.0,9132961.0,17234284.0,15151152.0,4942.0,...,11765330.0,11743594.0,8881454.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
first_dose = df[(df['Updated On'] == '09/08/2021') & (df['State'] != 'India')]

In [17]:
x = first_dose[['State','First Dose Administered']]

In [18]:
x.to_csv('FirstDoseIndia.csv', index = False)

In [19]:
# Second Dose

In [20]:
second_dose = df[(df['Updated On'] == '09/08/2021') & (df['State'] != 'India')]
x = second_dose[['State','Second Dose Administered']]
x.to_csv('SecondDoseIndia.csv', index = False)

In [21]:
# No. of male vaccinated

In [22]:
male = df['Male(Individuals Vaccinated)']

In [23]:
male.max()

134941971.0

In [24]:
# No. of Female vaccinated

In [25]:
female = df['Female(Individuals Vaccinated)']

In [26]:
female.max()

115668447.0